qt5-toolchain: add x11 and opengl to REQUIRED_DISTRO_FEATURES
Issue: LINCD-2345

This fixes errors:
    ERROR: Nothing RPROVIDES 'qtlocation-plugins' (but /home/wrlbuild/builds/builds-a09c8e41-9f61-43b0-80d0-602f061859df/layers/meta-qt5/recipes-qt/packagegroups/packagegroup-qt5-toolchain-target.bb RDEPENDS on or otherwise requires it)
    NOTE: Runtime target 'qtlocation-plugins' is unbuildable, removing...
    Missing or unbuildable dependency chain was: ['qtlocation-plugins']
    ERROR: Nothing RPROVIDES 'qtlocation-dev' (but /home/wrlbuild/builds/builds-a09c8e41-9f61-43b0-80d0-602f061859df/layers/meta-qt5/recipes-qt/packagegroups/packagegroup-qt5-toolchain-target.bb RDEPENDS on or otherwise requires it)
    NOTE: Runtime target 'qtlocation-dev' is unbuildable, removing...
    Missing or unbuildable dependency chain was: ['qtlocation-dev']

Adding REQUIRED_DISTRO_FEATURES to qtlocation_git is not enough
for the faw script to recognize them as qtlocation dependencies.
faw also needs it to be in packagegroup-qt5-toolchain-target,
as a number of qtlocation-* packages are runtime dependencies
for the toolchain-target.

(LOCAL REV: NOT UPSTREAM) -- wrlinux specific
Signed-off-by: Mingde (Matthew) Zeng <matthew.zeng@windriver.com>
Signed-off-by: Randy MacLeod <Randy.MacLeod@windriver.com>