qtlocation: add x11 and opengl to REQUIRED_DISTRO_FEATURES
x11 and opengl are required for qtlocation to build successfully.

Without opengl, do_compile will fail with error message:
    ../../include/QtLocation/5.15.0/QtLocation/private/../../../../../../git/src/location/declarativemaps/qdeclarativepolygonmapitem_p_p.h:168:17: error: 'const char* MapPolygonShader::fragmentShader() const' marked 'override', but does not override
    168 |     const char *fragmentShader() const override {
        |                 ^~~~~~~~~~~~~~
    ../../include/QtLocation/5.15.0/QtLocation/private/../../../../../../git/src/location/declarativemaps/qdeclarativepolygonmapitem_p_p.h: In member function 'virtual void MapPolygonShader::initialize()':
    ../../include/QtLocation/5.15.0/QtLocation/private/../../../../../../git/src/location/declarativemaps/qdeclarativepolygonmapitem_p_p.h:186:23: error: 'program' was not declared in this scope
    186 |         m_matrix_id = program()->uniformLocation("qt_Matrix");
        |                       ^~~~~~~

Note that program()->uniformLocation is part of QOpenGLShaderProgram
class, which depends on OpenGl.

When opengl is in the DISTRO_FEATURES, x11 is also needed, otherwise
it will fail with:
    | ERROR: Feature 'opengl-desktop' was enabled, but the pre-condition '(config.win32 && !config.winrt && !features.opengles2 && (config.msvc || libs.opengl))
    |                           || (!config.watchos && !config.win32 && !config.wasm && libs.opengl)' failed.
    |
    | ERROR: The OpenGL functionality tests failed!

Issue: LINCD-2286

(LOCAL REV: NOT UPSTREAM) -- wrlinux specific
Signed-off-by: Mingde (Matthew) Zeng <matthew.zeng@windriver.com>